FROM node:20-alpine

WORKDIR /app

# install deps first (cache layer)
COPY package.json package-lock.json ./
RUN npm ci

# env สำหรับ HMR ใน docker
ENV HOST=0.0.0.0
ENV PORT=3000
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

CMD ["npm", "run", "dev"]
